version: '3'
services:
  pg-packback-db:
    image: pg-packback-db:v0.0.4
    container_name: pg-packback-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - packbacknet

  packback:
    image: packback:v0.0.5
    container_name: packback
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    networks:
      - packbacknet
    depends_on:
      - "pg-packback-db"

networks:
  packbacknet:
    driver: bridge

volumes:
  postgres_data: